#!/bin/bash

aws_account_id=741335856197
aws_region=us-east-1
aws_vault_name=QNAP_Vault
cron_interval=10

script_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"

declare -A print_levels=([TRACE]=0 [DEBUG]=1 [INFO]=2 [WARN]=3 [ERROR]=4)
print_level="TRACE"
aws_echo=0  

printLevel() {
    local _log_priority=$1
    local _log_format="${@:2:1}"
    local _log_message="${*:3}"

    #check if level exists
    [[ ${print_levels[${_log_priority}]} ]] || return 1

    #check if level is enough
    (( ${print_levels[${_log_priority}]} < ${print_levels[${print_level}]} )) && return 2
 
    case ${_log_priority} in
    	TRACE|DEBUG|ERROR)
    		printf "%s (%s:%d): " "${_log_priority}" "${FUNCNAME[1]}" ${BASH_LINENO[0]}  >/dev/stderr
    		;;
    	INFO|WARN)
    		printf "%s: " "${_log_priority}" >/dev/stderr
    		;;
    esac

    printf "${_log_format}" ${_log_message} >/dev/stderr

}

awsCmd() {
	printLevel "TRACE" "aws ${*}\n"
	if [ -n "${aws_echo}" -a ${aws_echo} -ne 0 ]; then
		local _aws_out=$(mktemp)
		aws "$@" >${_aws_out}
		cat ${_aws_out} >/dev/stderr
		cat ${_aws_out}
		rm ${_aws_out}
	else
		aws "$@" 
	fi
}

isJobComplete() {
	printLevel "TRACE" "%s\n" "$@"
    local _jobs_file=$(mktemp)
	awsCmd glacier describe-job --vault-name ${aws_vault_name} --account-id ${aws_account_id} --job-id ${job_id} >${_jobs_file}
	local _completed=$(cat ${_jobs_file} | jq '.Completed')
	if [[ "${_completed}" == "true" ]]; then
		completion_date=$(cat ${_jobs_file} | jq '.CompletionDate' )
		printLevel "INFO" "isJobComplete: completion_date = %s\n" ${completion_date}
		rm ${_jobs_file}
		return 0
	else
		rm ${_jobs_file}
		return 1
	fi
}

getInventoryJobId() {
	printLevel "TRACE" "%s\n" "$@"
    _jobs_file=$(mktemp)
    awsCmd glacier list-jobs --vault-name ${aws_vault_name} --account-id ${aws_account_id} >${_jobs_file}
	job_id=$(cat ${_jobs_file} | jq ".JobList[0] | select(.StatusCode == \"InProgress\") | select(.Action == \"InventoryRetrieval\") | select(.VaultARN | contains(\"${aws_vault_name}\")) .JobId")
	creation_date=$(cat ${_jobs_file} | jq ".JobList[0] | select(.StatusCode == \"InProgress\") | select(.Action == \"InventoryRetrieval\") | select(.VaultARN | contains(\"${aws_vault_name}\")) .CreationDate")
	rm ${_jobs_file}
	if [ -n "${job_id}" ]; then
		printLevel "INFO" "Inventory JobId = %s\n" ${job_id}
		printLevel "INFO" "CreationDate    = %s\n" ${creation_date}
	else
		printLevel "INFO" "getInventoryJobId: job_id = <Not Found>\n" 
	fi
}

startInventory() {
	printLevel "TRACE" "%s\n" "$@"
	job_id=$(awsCmd glacier initiate-job --job-parameters '{"Type": "inventory-retrieval"}' --vault-name ${aws_vault_name} --account-id ${aws_account_id} --region ${aws_region} | jq '.jobId')
	printLevel "INFO" "job_id = %s\n" ${job_id}
}

setNextState() {
	printLevel "TRACE" "%s\n" "$@"
    # State is always the first parameter passed
    if [ -n "$1" ]; then  	
  		next_state=$1
  	else
    	getInventoryJobId
    	if [ -n "${job_id}" ]; then
      		# Job is in progress
      		next_state="STATUS"
    	else
      		# Inventory isn't running, so check to see if we were waiting for it to complete
      		cron_finish=$(cronSearch "0 0 1 1")
      		if [ -n "${_cron_finish}" ]; then
      			next_state="FINISH"
      		else
        		next_state="START"
      		fi
    	fi
  	fi
	printLevel "TRACE" "Next State = ${next_state}\n"
}

advanceState() {
	printLevel "TRACE" "%s\n" "$@"
	state=${next_state}
}

cronAdd() {
	printLevel "TRACE" "%s\n" "$@"
	# Schedule cronjob
	local _cron_file=$(mktemp)
	crontab -l >${_cron_file}
	printf "${1}\n" >> ${_cron_file}
	crontab ${_cron_file}
	cat ${_cron_file}
	rm ${_cron_file}
}

cronDel() {
	printLevel "TRACE" "%s\n" "$@"
	# Remove cronjob
	local _cron_file=$(mktemp)
	crontab -l | grep -v "${1}" >${_cron_file}
	crontab ${_cron_file}
	cat ${_cron_file}
	rm ${_cron_file}
}

cronSearch() {
	printLevel "TRACE" "%s\n" "$@"
	# Search cron table
    crontab -l | grep "${1}"
}

getJobOutput() {
	printLevel "TRACE" "%s\n" "$@"
	local _job_output=$(mktemp)
	awsCmd glacier get-job-output --vault-name ${aws_vault_name} --account-id ${aws_account_id} --region ${aws_region} --job-id ${job_id} ${_job_output}
	printf "%s" ${_job_output} 
	rm ${_job_output}
}

deleteArchives() {
	printLevel "TRACE" "%s\n" "$@"
    local _job_output="$(getJobOutput)"
	local _archive_ids=$(jq .ArchiveList[].ArchiveId < ${_job_output})
	archive_count=$(echo ${_archive_ids} | wc -w)
	local _loop_cnt=0
	for _archive_id in ${_archive_ids}; do
		_loop_cnt=$(( ${_loop_cnt} + 1 ))
	    awsCmd glacier delete-archive --archive-id=${archive_id} --vault-name ${aws_vault_name} --account-id ${aws_account_id} --region ${aws_region}
	done
}

printCompletionStats() {
	printLevel "TRACE" "%s\n" "$@"
    printLevel "INFO" "Job id %s started at %s, deleted %d archives from %s, and completed at %s\n" ${job_id} ${creation_date} ${archive_count} ${aws_vault_name} ${completion_date}
}

processState() {
	printLevel "TRACE" "%s\n" "$@"
	case ${state} in
		START)
    		# Initiate inventory and move to WAIT state
    		printf "Request Inventory?"
    		read
    		startInventory
    		# Delete any existing cronjobs
    		cronDel "${script_path}"
    		setNextState "WAIT"
    		# Schedule this to run again in ${cron_interval} minutes
    		cronAdd "*/${cron_interval} * * * * ${script_path} WAIT ${job_id} ${creation_date} ${archive_count} ${completion_date}"
    		exit
    		;;
  		STATUS)
    		# Display how long we've been waiting
            printLevel "INFO" "Inventory started at %s, job id %s.\n" "${creation_date} ${job_id}"
            printLevel "INFO" "Testing every %d minutes.\n" ${cron_interval}
            exit
    		;;
  		WAIT)
    		# If job_id is complete, advance to COMPLETE state
    		if isJobComplete; then
    			setNextState "COMPLETE"
    			local _cron_rule=$(cronSearch "${cron_task}")
    			cronDel "${_cron_rule}"
    		else
    			exit
    		fi
    		;;
  		COMPLETE)
    		# Delete archives, advance to FINISH state
    		deleteArchives
    		# Schedule cronjob to display output on 1/1 (it will be deleted if the user checks the status)
    		cronAdd "0 0 1 1 * ${script_path} FINISH ${job_id} ${creation_date} ${archive_count} ${completion_date}"
    		exit
    		;;
  		FINISH)
			if [ -z "${1}" ]; then
				local _last_args=$(printf "%s" "$(printf "%s" "${cron_finish}" | cut -f 6- -d ' ')")
				${script_path} ${_last_args}
			fi
			cronDel "0 0 1 1"
			;;
	esac
}

getArgs() {
	printLevel "TRACE" "%s\n" "$@"
    setNextState ${1}
    job_id=${job_id:-${2}}
    creation_date=${creation_date:-${3}}
    archive_count=${archive_count:-${4}}
    completion_date=${completion_date:-${5}}
}

main() {
    printLevel "INFO" "Started ${script_path} $@\n\n"
	printLevel "TRACE" "%s\n" "$@"

	# Global variables
	declare -g job_id
	declare -g creation_date
	declare -g archive_count
	declare -g completion_date
	declare -g cron_finish

    getArgs $@
    cron_task="${script_path} $@"

    while : ; do
	    advanceState
	    processState
        [[ "${state}" != "FINISH" ]] || break
    done
    printLevel "INFO" "Finished ${script_path} $@\n\n"
}

main $@

exit

OPT_WAIT=0
OPT_COMPLETE=0

if [[ "${OPTION}" == "--wait_job" ]]; then
	OPT_WAIT=1
	WAIT_JOB=$2
elif [[ "${OPTION}" == "--complete" ]]; then
	OPT_COMPLETE=1
	COMPLETE_JOB=$2
elif [[ "${OPTION}" == "--final" ]]; then
	COMPLETE_JOB=$2
	total=$3
	echo "Deleted ${total} archive records (Job Id: ${COMPLETE_JOB}) from Amazon ${aws_vault_name}"
	# Remove cronjob
	cron_file=$(mktemp)
	crontab -l | grep -v "${script_path}" | grep "\-\-final" | grep "$2" >${cron_file}
	crontab ${cron_file}
	rm  ${cron_file}
	exit
else
	final_call=$(crontab -l | grep "${script_path}" | grep "\-\-final" | grep "${COMPLETE_JOB}"|cut -f 6- -d ' ')
	if [ -n "${final_call}" ]; then
	    ${final_call}
	    exit
	fi
fi


job_list_file=$(mktemp)
aws_cmd glacier list-jobs --vault-name ${aws_vault_name} --account-id ${aws_account_id} >${job_list_file}
#running_job=$(cat ${job_list_file} | jq '.JobList[] | select(.StatusCode == "InProgress") .JobId')

# If we're waiting on a particular job
if [ -n "${WAIT_JOB}" ]; then
	running_job=$(cat ${job_list_file} | jq '.JobList[] | select(.StatusCode == "InProgress") | select(.JobId == "${WAIT_JOB}").JobId')
else
	running_job=$(cat ${job_list_file} | jq '.JobList[] | select(.StatusCode == "InProgress") | select(.Action == "InventoryRetrieval").JobId')
fi

if [ -n "${running_job}" ]; then
	if [ ${OPT_WAIT} -eq 1 ]; then
		echo "Waiting for ArchiveInventory to complete."
	elif [ ${OPT_FORCE} -eq 0 ]; then
		# We just want a status, then exit
		cronjob_done=$(grep "${script_path}" <(crontab -l))
		if [ -n "${cronjob_done}" ]; then
			# Print when job started 
			echo "Job stated on ..."
		fi
		exit
	fi

	exit
elif [ ${OPT_WAIT} -eq 1 ]; then
    # The job completed

	# Remove cronjob
	cron_file=$(mktemp)
	crontab -l | grep -v "${script_path}" >${cron_file}
	crontab ${cron_file}
	rm  ${cron_file}

	# Finish up
    ${script_path} --complete ${WAIT_JOB}
    exit
fi

# Initiate job
if [ ${OPT_COMPLETE} -eq 0 ]
	NEW_JOB=$(${aws_cmd} glacier initiate-job --job-parameters \'{"Type": "inventory-retrieval"}\' --vault-name ${aws_vault_name} --account-id ${aws_account_id} --region ${aws_region} | jq '.JobId')
	# Schedule cronjob
	cron_file=$(mktemp)
	crontab -l >${cron_file}
	echo "0/10 * * * * ${script_path} --wait_job ${NEW_JOB}" >> ${cron_file}
	crontab ${cron_file}
	rm ${cron_file}
else
	output=$(mktemp)
	${aws_cmd} glacier get-job-output --vault-name ${aws_vault_name} --account-id ${aws_account_id} --region ${aws_region} --job-id ${COMPLETE_JOB} ${output}


	archive_ids=$(jq .ArchiveList[].ArchiveId < ${output})
	total=$(echo ${archive_ids} | wc -w)
	cnt=0
	for archive_id in ${archive_ids}; do
		cnt=$(( $cnt + 1 ))
	    echo "Deleting Archive: ${cnt} of ${total} - ${archive_id}"
	    ${aws_cmd} glacier delete-archive --archive-id=${archive_id} --vault-name ${aws_vault_name} --account-id ${aws_account_id} --region ${aws_region}
	done
	rm ${output}
	# Schedule cronjob to display output
	cron_file=$(mktemp)
	crontab -l >${cron_file}
	echo "0 0 1 1 * ${script_path} --final ${COMPLETE_JOB} ${total} " >> ${cron_file}
	crontab ${cron_file}
	rm ${cron_file}
fi

echo "Finished deleting archives"
# https://github.com/leeroybrun/glacier-vault-remove
#aws_credentials_json='/home/chris/.aws/credentials.json'
#docker run -v ${aws_credentials_json}:/app/credentials.json -d leeroyb/glacier-vault-remove ${aws_region} [${aws_vault_name}|LIST] [DEBUG] [NUM_PROCESSES] [<job_id>|LIST|NEW|LATEST]
#docker run -v ${aws_credentials_json}:/app/credentials.json -d leeroyb/glacier-vault-remove ${aws_region} ${aws_vault_name} DEBUG 10
#exit

state_START